name: Run isort
on:
  - push
  - pull_request

jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: isort/isort-action@master
        with:
            requirements-files: "requirements.txt requirements-test.txt"
            configuration: "--profile black"
